In [7]:
import numpy as np
import pandas as pd
from pandas import DataFrame, Series
from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

from sklearn.impute import SimpleImputer
from feature_engine.wrappers import SklearnTransformerWrapper

In [8]:
class feature_engine.wrappers.SklearnTransformerWrapper(variables=None, transformer=None)

SyntaxError: invalid syntax (<ipython-input-8-afcd9c6908d1>, line 1)

In [11]:
# Load dataset
data = pd.read_csv('houseprice.csv')

# Separate into train and test sets
X_train, X_test, y_train, y_test = train_test_split(
    data.drop(['Id', 'SalePrice'], axis=1),
    data['SalePrice'], test_size=0.3, random_state=0)

# set up the wrapper with the SimpleImputer
imputer = SklearnTransformerWrapper(transformer = SimpleImputer(strategy='mean'),
                                    variables = ['LotFrontage', 'MasVnrArea'])

# fit the wrapper + SimpleImputer
imputer.fit(X_train)

# transform the data
t_train = imputer.transform(X_train)
t_test = imputer.transform(X_test)

In [14]:
X_train[X_train['LotFrontage'].isnull()]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
64,60,RL,NaN,9375,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,GdPrv,NaN,0,2,2009,WD,Normal
682,120,RL,NaN,2887,Pave,NaN,Reg,HLS,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,11,2008,WD,Normal
853,80,RL,NaN,12095,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,MnPrv,NaN,0,8,2009,WD,Normal
328,75,RL,NaN,11888,Pave,Pave,IR1,Bnk,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,7,2009,WD,Normal
452,60,RL,NaN,9303,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,0,NaN,NaN,NaN,0,7,2007,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
845,85,RL,NaN,16647,Pave,NaN,IR1,Lvl,AllPub,CulDSac,...,0,0,NaN,NaN,NaN,0,1,2007,WD,Normal
537,20,RL,NaN,12735,Pave,NaN,IR1,Lvl,AllPub,FR2,...,0,0,NaN,MnWw,NaN,0,4,2008,COD,Normal
1033,20,RL,NaN,8125,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,2,2006,WD,Normal
1383,30,RL,NaN,25339,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,8,2007,WD,Normal
559,120,RL,NaN,3196,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal

In [15]:
t_train.loc[[64,682,559]]

,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,LotConfig,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
64,60,RL,69.668667,9375,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,GdPrv,NaN,0,2,2009,WD,Normal
682,120,RL,69.668667,2887,Pave,NaN,Reg,HLS,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,11,2008,WD,Normal
559,120,RL,69.668667,3196,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,0,NaN,NaN,NaN,0,10,2006,WD,Normal

In [17]:
X_train['LotFrontage'].mean()  # we can see above that LotFrontage NULL is replaced with mean value 69.66

69.66866746698679